### ISSUE TITLE
Consider support circle?

### ISSUE THREAD

**Issue by shuoli84** [tiby312/poloto#136]
https://www.w3schools.com/graphics/svg_circle.asp
Useful for plot dots on chart with different colors.

**Comment by tiby312** [comment]
@shuoli84 

Right now you can make the dots in the scatter plot big by changing the stroke width. You can also have each plot have a different color. 

[source](https://github.com/tiby312/poloto/blob/master/examples/large_scatter.rs)
[rendered](https://github.com/tiby312/poloto/blob/master/target/assets/large_scatter.svg)


You unfortunately can't fill it with different color than the stroke because they are just lines with a length of zero. I at one point had it use circles, but i changed it because its not very dense in the svg file. Whereas if you use path, its pretty dense. Like if you have 100 points, there's a lot of text duplication with circle tag. 

Is what you're looking for the ability to have scatter dots where you can fill it in and also have a stroke around it? It didn't occur to me that by going path route this ability is lost.
